// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyOIA8o2gmZFF_cHzw2c6URq-3AgBZvxw',
    appId: '1:197683276536:web:101ed63a10ed9310c3690d',
    messagingSenderId: '197683276536',
    projectId: 'project-cipher-2b32a',
    authDomain: 'project-cipher-2b32a.firebaseapp.com',
    storageBucket: 'project-cipher-2b32a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkVkkYY1O4R1cMPPtz-CHvOHyGELkj_QU',
    appId: '1:197683276536:android:ce4ccad592388999c3690d',
    messagingSenderId: '197683276536',
    projectId: 'project-cipher-2b32a',
    storageBucket: 'project-cipher-2b32a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwYv5hgDzcVwqxhEY8XkOoNGJXK6Okkhs',
    appId: '1:197683276536:ios:8eaaee1b435db22ac3690d',
    messagingSenderId: '197683276536',
    projectId: 'project-cipher-2b32a',
    storageBucket: 'project-cipher-2b32a.firebasestorage.app',
    iosBundleId: 'com.example.projectcipher.projectCipher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwYv5hgDzcVwqxhEY8XkOoNGJXK6Okkhs',
    appId: '1:197683276536:ios:8eaaee1b435db22ac3690d',
    messagingSenderId: '197683276536',
    projectId: 'project-cipher-2b32a',
    storageBucket: 'project-cipher-2b32a.firebasestorage.app',
    iosBundleId: 'com.example.projectcipher.projectCipher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyOIA8o2gmZFF_cHzw2c6URq-3AgBZvxw',
    appId: '1:197683276536:web:2a8b74a765dfececc3690d',
    messagingSenderId: '197683276536',
    projectId: 'project-cipher-2b32a',
    authDomain: 'project-cipher-2b32a.firebaseapp.com',
    storageBucket: 'project-cipher-2b32a.firebasestorage.app',
  );
}
